### ISSUE TITLE
Each invocation uses a different temporary directory

### ISSUE THREAD

**Issue by mattgodbolt** [uilianries/conan-libpcap#10]
I built locally and it seems like no includes or libraries actually got packaged:

```
Packaging to aeee4f382a3c948e1e86eb20bdd4e83c11a2236a
libpcap/1.8.1@coinbase/stable: Generating the package
libpcap/1.8.1@coinbase/stable: Package folder /tmp/tmpym13c438/.conan/data/libpcap/1.8.1/coinbase/stable/package/aeee4f382a3c948e1e86eb20bdd4e83c11a2236a
libpcap/1.8.1@coinbase/stable: Calling package()
libpcap/1.8.1@coinbase/stable package(): Copied 1 file: LICENSE
libpcap/1.8.1@coinbase/stable: Package 'aeee4f382a3c948e1e86eb20bdd4e83c11a2236a' created
```

similarly when I tried to include it in another package no include paths or libraries were brought in.

**Comment by mattgodbolt** [comment]
Must be an issue with my automated build: manually cloning this project and running it manually worked just fine. Sorry!

**Comment by mattgodbolt** [comment]
Seems it's because my script runs `conan source` and then `conan build` and then `conan export-pkg` -- the temporary directory `install_dir` is different every invocation of `conan` so the results of the `build` step aren't available when packaging!

Changing the `install_dir` to be something like `os.getcwd() + "/install"`  "fixed" this. Not sure what the right approach is; this is the first conan recipe that I've had this problem with.

**Comment by uilianries** [comment]
Hi @mattgodbolt , please follow the instructions from here:

https://github.com/uilianries/conan-libpcap/issues/9#issuecomment-478114882

BTW, AFAIK libpcap is working well. When I created this recipe, I needed to sniff some networking data packages for embedded devices.

If you find any bug, or want to discuss about a new feature, please, open an issue for Bincrafters:

https://github.com/bincrafters/community/issues

I'm able to answer there too.

Best Regards!

**Comment by mattgodbolt** [comment]
Thanks!
