### ISSUE TITLE
sudo required for build?

### ISSUE THREAD

**Issue by mattgodbolt** [uilianries/conan-libpcap#9]
When trying to build in a Centos docker:

```
package bison is not installed
package flex is not installed
Running: sudo -A yum update -y
sh: sudo: command not found
ERROR: libpcap/1.8.1@PROJECT: Error in build_requirements() method, line 35
	package_tool.install(packages="bison flex")
	ConanException: Command 'sudo -A yum update -y' failed
```

**Comment by mattgodbolt** [comment]
Maybe a duplicate of #7 ?

**Comment by uilianries** [comment]
Hi @mattgodbolt !

Please, use Bincrafters' package instead:

    conan install libpcap/1.8.1@bincrafters/stable

The recipe is here: https://github.com/bincrafters/conan-libpcap
If you check the recipe, both flex and bison are Conan packages ;)

My repo is first draft of pcap recipe and it's really outdated.

Best regards!

**Comment by mattgodbolt** [comment]
Thanks @uilianries ! I googled a few times but only this repo turned up. For my own reasons I need to build the packages from source, and so I'll use the `conan-libpcap` repo! thanks so much!
